CCPLUS_FILTER(4color)
CCPLUS_FILTER(ramp)
CCPLUS_FILTER(mask)

CCPLUS_FILTER(4corner)
CCPLUS_FILTER(transform)
CCPLUS_FILTER(gaussian)
CCPLUS_FILTER(hsl)
CCPLUS_FILTER(fill)
CCPLUS_FILTER(grayscale)

CCPLUS_FILTER(volume)
