/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_ccme_ccplus_CCPlay */

#ifndef _Included_cc_ccme_ccplus_CCPlay
#define _Included_cc_ccme_ccplus_CCPlay
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cc_ccme_ccplus_CCPlay
 * Method:    play
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_cc_ccme_ccplus_CCPlay_play
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     cc_ccme_ccplus_CCPlay
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_ccme_ccplus_CCPlay_stop
  (JNIEnv *, jclass);

/*
 * Class:     cc_ccme_ccplus_CCPlay
 * Method:    setBufferDuration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cc_ccme_ccplus_CCPlay_setBufferDuration
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
